package javamodule3;

import javax.swing.table.DefaultTableModel;

public class Design extends javax.swing.JFrame {

	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Design.class.getName());

	DefaultTableModel model;
	int productCounter = 1;
	double grandTotal = 0;

	/**
	 * Creates new form Design
	 */
	private void addProduct(String name, double price) {
		boolean found = false;

		for (int i = 0; i < model.getRowCount(); i++) {
			String existingProduct = model.getValueAt(i, 1).toString();

			if (existingProduct.equals(name)) {
				int qty = Integer.parseInt(model.getValueAt(i, 2).toString());
				qty++;

				double newTotal = qty * price;

				model.setValueAt(qty, i, 2);        // update quantity
				model.setValueAt(newTotal, i, 4);   // update total

				found = true;
				break;
			}
		}

		// If product not found, add new row
		if (!found) {
			model.addRow(new Object[]{
				productCounter++,
				name,
				1,
				price,
				price
			});
		}

		// Recompute grand total
		grandTotal = 0;
		for (int i = 0; i < model.getRowCount(); i++) {
			grandTotal += Double.parseDouble(model.getValueAt(i, 4).toString());
		}

		total.setText(String.valueOf(grandTotal));
	}

	public Design() {
		initComponents();

		model = (DefaultTableModel) listProduct.getModel();

		// BUTTON ACTIONS
		btnWater.addActionListener(e -> addProduct("Water", 10));
		btnCola.addActionListener(e -> addProduct("Cola", 20));
		btnIcecream.addActionListener(e -> addProduct("Ice Cream", 30));
		btnChocolate.addActionListener(e -> addProduct("Chocolate", 25));
		btnFries.addActionListener(e -> addProduct("Fries", 50));
		btnBurger.addActionListener(e -> addProduct("Burger", 80));
		btnTempura.addActionListener(e -> addProduct("Tempura", 60));
		btnCake.addActionListener(e -> addProduct("Cake", 40));
		btnCrossaint.addActionListener(e -> addProduct("Croissant", 45));
		btnMatcha.addActionListener(e -> addProduct("Matcha", 70));
		btnBoba.addActionListener(e -> addProduct("Boba", 65));
		btnApplejuice.addActionListener(e -> addProduct("Apple Juice", 35));

		// CLEAR BUTTON
		btnClear.addActionListener(e -> {
			model.setRowCount(0);
			grandTotal = 0;
			productCounter = 1;
			total.setText("");
		});

		// PAY BUTTON
		btnPay.addActionListener(e -> {
			javax.swing.JOptionPane.showMessageDialog(this,
					"Total Payment: ₱" + grandTotal,
					"Payment Successful",
					javax.swing.JOptionPane.INFORMATION_MESSAGE
			);

			model.setRowCount(0);
			grandTotal = 0;
			productCounter = 1;
			total.setText("");
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnWater = new javax.swing.JButton();
        btnCola = new javax.swing.JButton();
        btnIcecream = new javax.swing.JButton();
        btnChocolate = new javax.swing.JButton();
        btnFries = new javax.swing.JButton();
        btnBurger = new javax.swing.JButton();
        btnTempura = new javax.swing.JButton();
        btnCake = new javax.swing.JButton();
        btnCrossaint = new javax.swing.JButton();
        btnMatcha = new javax.swing.JButton();
        btnBoba = new javax.swing.JButton();
        btnApplejuice = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProduct = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Food Truck Dashboard");
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Early Dawn's Food Truck");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(440, 582));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(440, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Available Products:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(440, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(22, 342));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(22, 342));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(4, 3, 16, 22));

        btnWater.setBackground(new java.awt.Color(51, 51, 51));
        btnWater.setForeground(new java.awt.Color(255, 255, 255));
        btnWater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/water-bottle.png"))); // NOI18N
        btnWater.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Water", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnWater.addActionListener(this::btnWaterActionPerformed);
        jPanel4.add(btnWater);

        btnCola.setBackground(new java.awt.Color(51, 51, 51));
        btnCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/can.png"))); // NOI18N
        btnCola.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cola", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnCola);

        btnIcecream.setBackground(new java.awt.Color(51, 51, 51));
        btnIcecream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/chocolate.png"))); // NOI18N
        btnIcecream.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ice cream", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnIcecream);

        btnChocolate.setBackground(new java.awt.Color(51, 51, 51));
        btnChocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/chocolate-bar.png"))); // NOI18N
        btnChocolate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chocolate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnChocolate);

        btnFries.setBackground(new java.awt.Color(51, 51, 51));
        btnFries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/french-fries.png"))); // NOI18N
        btnFries.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fries", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnFries);

        btnBurger.setBackground(new java.awt.Color(51, 51, 51));
        btnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/burger.png"))); // NOI18N
        btnBurger.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Burger", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnBurger.addActionListener(this::btnBurgerActionPerformed);
        jPanel4.add(btnBurger);

        btnTempura.setBackground(new java.awt.Color(51, 51, 51));
        btnTempura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/food (1).png"))); // NOI18N
        btnTempura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tempura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnTempura);

        btnCake.setBackground(new java.awt.Color(51, 51, 51));
        btnCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/cake-slice.png"))); // NOI18N
        btnCake.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cake", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnCake);

        btnCrossaint.setBackground(new java.awt.Color(51, 51, 51));
        btnCrossaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/croissant.png"))); // NOI18N
        btnCrossaint.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Croissant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnCrossaint);

        btnMatcha.setBackground(new java.awt.Color(51, 51, 51));
        btnMatcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/matcha-latte.png"))); // NOI18N
        btnMatcha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matcha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnMatcha.addActionListener(this::btnMatchaActionPerformed);
        jPanel4.add(btnMatcha);

        btnBoba.setBackground(new java.awt.Color(51, 51, 51));
        btnBoba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/bubble-tea.png"))); // NOI18N
        btnBoba.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Boba", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnBoba);

        btnApplejuice.setBackground(new java.awt.Color(51, 51, 51));
        btnApplejuice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javamodule3/juice-box.png"))); // NOI18N
        btnApplejuice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apple juice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(btnApplejuice);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        listProduct.setBackground(new java.awt.Color(204, 204, 255));
        listProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product No.", "Product Name", "Qty", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(listProduct);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Product Selected:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total:");

        total.addActionListener(this::totalActionPerformed);

        btnPay.setText("PAY");
        btnPay.addActionListener(this::btnPayActionPerformed);

        btnClear.setText("CLEAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPay)
                    .addComponent(btnClear))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchaActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_btnMatchaActionPerformed

    private void btnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBurgerActionPerformed

    private void btnWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWaterActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new Design().setVisible(true));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplejuice;
    private javax.swing.JButton btnBoba;
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnCake;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCola;
    private javax.swing.JButton btnCrossaint;
    private javax.swing.JButton btnFries;
    private javax.swing.JButton btnIcecream;
    private javax.swing.JButton btnMatcha;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnTempura;
    private javax.swing.JButton btnWater;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listProduct;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
